### ISSUE TITLE
Add ability to search through a database of all of other people's public active ideas

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/crafting-ideas#18]
We can add a search bar that will allow to search through an open database of all ideas that were marked of as 'public' and people are working or want to work on.

**Comment by massens** [comment]
Yes, 'Search' makes a lot of sense. Maybe also 'Explore', where you don't necessarily know what you're looking for, you just want to see cool things (i.e. [Git Hub's explore](https://github.com/explore))
